# Test installing from conda-forge

name: Install & test conda-forge package
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        python-version: [ 3.7, 3.8, 3.9 ]
    steps:
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
        channel-priority: true
        activate-environment: test
        mamba-version: "*"
    - name: Install geedim
      run: |
        mamba info
        mamba list
        mamba install -c conda-forge geedim>=1.5.1
        mamba list
    - name: Test geedim
      timeout-minutes: 5
      env:
        EE_SERVICE_ACC_PRIVATE_KEY: ${{ secrets.EE_SERVICE_ACC_PRIVATE_KEY }}
      run: |
          geedim --version
          geedim --help
          geedim search --help
          geedim search -c l8-c2-l2 -s 2019-02-01 -e 2019-03-01 --bbox 23 -33 23.2 -33.2 composite -cm q-mosaic --mask download --scale 30 --crs EPSG:3857 -o
          test -f ./data/test_example/homogenised/3324c_2015_1004_05_0182_RGB_HOMO_cREF_mGAIN-BLK-OFFSET_k5_5.tif && echo "Test OK"
          pwd
          ls -R
